### ISSUE TITLE
Unable to find local image

### ISSUE THREAD

**Issue by alexfoias** [neuropoly/sct_docker#1]
I opened Docker for Windows.
I cloned the repo https://github.com/neuropoly/sct_docker on the machine.
When trying to run the docker I get the following error.
```
PS C:\Users\alfoi_admin\sct_docker_test\sct_docker-master> docker run -p 2222:22 --rm -it --name sct_ssh neuropoly/sct
Unable to find image 'neuropoly/sct:latest' locally
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
```

**Comment by poquirion** [comment]
@alexfoias, you need to build the image first. We could also have a neuropoly repo on docker hub and push the image there. 

Its in the README
```
docker build --tag neuropoly/sct .
```

**Comment by alexfoias** [comment]
@poquirion It worked. Building the image took around 15 min on the windows machine. PC configuration:  i3-7100 processor, 8Gb RAM, HDD 1TB (64MB Cache) 7200 RPM SATA 6Gb/s.
