### ISSUE TITLE
Trouble starting Xming (Docker Desktop)

### ISSUE THREAD

**Issue by Aaronearlerichardson** [neuropoly/sct_docker#12]
My Xming terminal seems to open and then instantly close now. Let me retrace my steps since there is no error code to show you.

I have completed the docker installation on my windows 10 machine as well as Xming. I installed the sct with the code:
`docker pull neuropoly/sct:sct-3.2.3-official`
and I created the `C:/Users/docker_shared_folder`

I can successfully use sct after running this code in the CMD.
`docker run -p 2222:22 --rm -it -v //c/Users/docker_shared_folder://home/sct/docker_shared_folder neuropoly/sct:sct-3.2.3-official` 

I installed and used the Xming program by running `sct-win.xlaunch` and it worked fine except when I tried transferring files to the shared folder on the windows side it never showed up on the linux side. I decided to try restarting my computer. Once I did I reran docker and made sure it was using the linux containers. I tried running the Xming executable but it seems to open and then near instantly close. I can faintly make out the words `connection failed` after trying it a couple of times docker is running fine. I've tried uninstalling and reinstalling Xming with no change. The CMD usage still works fine but I need to use fsleyes. What should I do? Thanks!

**Comment by zougloub** [comment]
1. From what you said I'm assuming you're running Docker on Windows pro
2. Let's see why this "connection failed" happens.  
Can you run git bash on the host, do `ssh -p 2222 -Y sct@127.0.0.1` (which is what the sct-win.xlaunch script uses to get X11 display forwarding), and let us know what happens?
3. Can you run "sudo netstat -nlp" on the Docker guest and check if you have this line:  
`tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2578/sshd           `?  
Normally an SSH service is running when you open the interactive docker session.

Thanks,

**Comment by Aaronearlerichardson** [comment]
Yes I am running pro

Here's what happened when I ran step 2:
```
>ssh -p 2222 -Y sct@127.0.0.1
ssh: connect to host 127.0.0.1 port 2222: Connection refused
```
I assume by docker guest you mean what happens when I run this code
```
docker run -p 2222:22 --rm -it -v //c/Users/docker_shared_folder://home/sct/docker_shared_folder neuropoly/sct:sct-3.2.3-official
```
and I tried running `sudo netstat -nlp` but it doesn't recognize netstat
```
sct@baab273c92a1:~$ sudo netstat -nlp
sudo: netstat: command not found
```
Is this not the docker guest you're talking about?

**Comment by zougloub** [comment]
`ssh: connect to host 127.0.0.1 port 2222: Connection refused` is the problem, we don't know why it's not working yet.

I hadn't realized that `netstat` wasn't available; you can install it by doing
`sct@5a9ec74a62d3:~$ sudo apt install net-tools`
Then you should see:
```
sct@5a9ec74a62d3:~$ sudo netstat -nlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      12/sshd             
tcp6       0      0 :::22                   :::*                    LISTEN      12/sshd             
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
```
If this is shown, then we have a problem with docker forwarding; else the problem is that SSH not running, we'll see for next steps.

**Comment by Aaronearlerichardson** [comment]
I tried installing net-tools and this happened 
```
sct@e7a9f5342497:~$ sudo apt install net-tools
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 23 not upgraded.
Need to get 194 kB of archives.
After this operation, 803 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 net-tools amd64 1.60+git20161116.90da8a0-1ubuntu1
  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20161116.90da8a0-1ubuntu1_amd64.deb  404  Not Found [IP: 91.189.88.161 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
sct@e7a9f5342497:~$ sudo apt install net-tools --fix-missing
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 23 not upgraded.
Need to get 194 kB of archives.
After this operation, 803 kB of additional disk space will be used.
Err:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 net-tools amd64 1.60+git20161116.90da8a0-1ubuntu1
  404  Not Found [IP: 91.189.88.161 80]
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20161116.90da8a0-1ubuntu1_amd64.deb  404  Not Found [IP: 91.189.88.161 80]
E: Internal Error, ordering was unable to handle the media swap
sct@e7a9f5342497:~$ sudo apt-get update
Ign:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Ign:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Err:3 http://security.ubuntu.com/ubuntu bionic-security Release
  404  Not Found [IP: 91.189.88.162 80]
Ign:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Ign:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Err:6 http://archive.ubuntu.com/ubuntu bionic Release
  404  Not Found [IP: 91.189.88.161 80]
Err:7 http://archive.ubuntu.com/ubuntu bionic-updates Release
  404  Not Found [IP: 91.189.88.161 80]
Err:8 http://archive.ubuntu.com/ubuntu bionic-backports Release
  404  Not Found [IP: 91.189.88.161 80]
Reading package lists... Done
E: The repository 'http://security.ubuntu.com/ubuntu bionic-security Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-updates Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
E: The repository 'http://archive.ubuntu.com/ubuntu bionic-backports Release' no longer has a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by zougloub** [comment]
Standard Ubuntu error message, you can update the package database by doing `sudo apt update` prior to retrying the installation.

**Comment by zougloub** [comment]
You're really unlucky. `sudo apt update` works for me without the HTTP 404 errors, and that http://archive.ubuntu.com/ubuntu/pool/main/n/net-tools/net-tools_1.60+git20161116.90da8a0-1ubuntu1_amd64.deb is reachable.

**Comment by Aaronearlerichardson** [comment]
I figured out it had something to do with the specific WIFI connection I was using, I installed netstat and now Xming is working fine. Here is the result of `sudo netstat -nlp`
```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:6010            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      13/sshd             
tcp6       0      0 :::6010                 :::*                    LISTEN      -                   
tcp6       0      0 :::22                   :::*                    LISTEN      13/sshd             
Active UNIX domain sockets (only servers)
Proto RefCnt Flags       Type       State         I-Node   PID/Program name     Path
unix  2      [ ACC ]     STREAM     LISTENING     24719    -                    /home/sct/.cache/.lxterminal-socket-e7a9f5342497:10.0
```
The only thing that is still not working is the docker shared folder doesn't seem to actually be sharing files between systems. What should I do to fix this?

**Comment by zougloub** [comment]
To be continued in #13
