### ISSUE TITLE
Windows shared folders not working (Toolbox)

### ISSUE THREAD

**Issue by zougloub** [neuropoly/sct_docker#13]
The docker shared folder doesn't seem to actually be sharing files between systems.

Follow-up of #12.

**Comment by zougloub** [comment]
Reproduced the problem on my end following the installation instructions:

- `~/docker_shared_folder` starts by being root-owned and with 755 permissions
- changed permissions to be able to write to it
- wrote inside -> no file appeared in Windows
- wrote in Windows folder -> no file appearing on Linux side

**Comment by CRMBMuser** [comment]
Hello everybody,

Is this issue still opened?

I recently tried to pull the SCT v3.2.2 on Docker Quickstart Terminal.
I followed all installation steps and the following command is working:

‘docker run -p 2222:22 --rm -it -v //c/Users/docker_shared_folder://home/sct/docker_shared_folder neuropoly/sct:sct-3.2.2-official’

On windows host, I’ve shared C:/Users/docker_shared_folder in the VM configuration tab (docker_shared_folder is the name). Still, I can’t share any data between Windows and Linux (and vice versa) and I can’t launch Xming. I feel like it is indeed a permission issue yet I haven’t been able to fix it. I’ve tried the mount command on Linux VM but without success so far.

Does anybody have any insights of what I should do? Thank you very much for your help!

Best,

**Comment by zougloub** [comment]
Hi @CRMBMuser,

Actually the issue is fixed on Docker for Windows (ie. not Home), but I don't have anything to test in the Docker Toolbox environment. Just to be sure, are you really running the Windows Home version?

PS: for those who may have had the issue on Windows "pro", please have a look at the [changes in the README](https://github.com/neuropoly/sct_docker/commit/930a23681d30ac8d1f3638e3150f2cfe458851fc), the notable things are:

- The volume should be made available to Docker
- Double slash in volume syntax (you had it)
- The folder (`c:\Users\docker_shared_folder`) should be made writable for anybody through the folder properties security tab (or else you can read, but not write).

**Comment by CRMBMuser** [comment]
Hi @zougloub,

Thank you for your answer! Actually I'm on Win7 Pro.

This might have been a slight misunderstanding on my end when I read the README because I installed Docker Toolbox and not Docker. I thought Docker was only compatible for Win10 Pro.

I did two things following you message: 

- Made the volume C: available in the ‘shared folder’ configuration tab of the ‘default’ VM.
- Change permission in the security tab for the folder (c:\Users\docker_shared_folder) to make it writable for anybody.

Unfortunately, I haven’t seen any changes so far for sharing files between the two systems.

Do you think I should switch to Docker instead?
Should I use the ‘mount’ command in Linux?

Thank you for your patience!

Best,

**Comment by alexfoias** [comment]
With the help of @lrouhier, the shared docker folder has the correct permissions. 

Right click on the docker_shared_folder-Properties-Security. And grant full control for everyone.

See the screenshots here: 
![Screen Shot 2019-08-01 at 2 06 42 PM](https://user-images.githubusercontent.com/12564433/62316693-0aa8a880-b466-11e9-94b9-9bc9d1905da3.png)

![Screen Shot 2019-08-01 at 2 06 36 PM](https://user-images.githubusercontent.com/12564433/62316701-0f6d5c80-b466-11e9-8a8b-b6a4b1fdd20e.png)

**Comment by zougloub** [comment]
Maybe Docker Toolbox (or VirtualBox) creates a Docker user, which could be used instead of Everyone?

**Comment by lrouhier** [comment]
I just tried it and I think that allowing only the current user and system is enough.

**Comment by jcohenadad** [comment]
great, so if this issue is solved, can you please update the documentation?

**Comment by lrouhier** [comment]
That's not enough for toolbox. I think I found a workaround (thanks to [this website](http://support.divio.com/en/articles/646695-how-to-use-a-directory-outside-c-users-with-docker-toolbox-docker-for-windows)  )

<b>Mount an arbitrary host directory in a Docker container</b>
- Stop Docker Machine if it's running, with docker-machine stop.
- In VirtualBox, add a Shared Folder: Settings > Shared Folders > Add share - this will be the directory where you want to locate your project, such as C:\User\shared_folder. check his name.
![image](https://user-images.githubusercontent.com/22171999/62324838-519f9980-b478-11e9-983b-f5392dceddfc.png)


-Restart Docker Machine, with docker-machine start.
-SSH into the Docker Machine, with docker-machine ssh.
- Create a directory in the machine as a mount point for the project directories, for example: mkdir projects. This will be /home/docker/projects - you can verify it by running pwd.

- Mount the Shared Folder you named above (docker_shared_folder) at the mount point you have created: sudo mount -t vboxsf -o uid=1000,gid=50 docker_shared_folder /home/docker/projects

- open a new quickstart terminal.
- run docker run -p 2222:22 --rm -it -v /home/docker/projects://home/sct/docker_shared_folder neuropoly/sct:sct-v4.0.0-beta.0-ubuntu-18.04

the docker shared folder correspond to the one in your user folder

if you cant' write inside check the permisiion from the windows host as @alexfoias  mentionned.

**Comment by jcohenadad** [comment]
hum... i wasn't aware we also had VirtualBox dependency for sct-docker (with Docker Toolbox). Is that so? Or maybe Docker Toolbox is somewhat related to VirtualBox?

**Comment by lrouhier** [comment]
Yes docker toolbox Is running on a VM that he created with virtualbox

**Comment by jcohenadad** [comment]
ok, so if this workaround works, i suggest we document it, unless @zougloub has something to say

**Comment by zougloub** [comment]
Please submit a merge request with updated documentation @lrouhier :+1:

**Comment by jcohenadad** [comment]
@lrouhier any update on this?

**Comment by lrouhier** [comment]
I'm writing it right now. I will open a PR when it's done.

**Comment by lrouhier** [comment]
I need access to the repository to push the change into my new branch.

**Comment by jcohenadad** [comment]
> I need access to the repository to push the change into my new branch.

you've just been invited

**Comment by jcohenadad** [comment]
Fixes by #34, #36
