### ISSUE TITLE
Docker pull doesn't work

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/sct_docker#14]
i use docker toolbox and the docker command docker pull neuropoly/sct:sct-3.2.4-official yield an error :Error response from daemon: manifest for neuropoly/sct:sct-3.2.4-official not found

I work on windows 10 if that helps. should i just download it locally ?

thanks in advance

**Comment by lrouhier** [comment]
OK using neuropoly/sct:sct-3.2.2-official seems to work as indicate on the docker page. Is there a new release or is that a typo ?

**Comment by zougloub** [comment]
Hi @lrouhier,

Hadn't realized that 3.2.4 hadn't be pushed to https://hub.docker.com/r/neuropoly/sct/tags/

Re-building and pushing.

**Comment by zougloub** [comment]
3.2.4 was finally built and pushed.

There were some issues with generating the Docker images and I was lacking the time to handle them.
