### ISSUE TITLE
ssh: Could not resolve hostname localhost:2222: Name or service not known

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_docker#20]
i followed this: https://github.com/neuropoly/sct_docker#id8

when running this:
~~~
ssh -Y sct@localhost:2222
~~~

i got this:
~~~
ssh: Could not resolve hostname localhost:2222: Name or service not known
~~~

**Comment by zougloub** [comment]
@jcohenadad still applicable?

**Comment by jcohenadad** [comment]
yes, i tried it again and run into the same issue. A bit more verbose:

Station: OSX Mojave
Opened Terminal, ran:
~~~
docker pull neuropoly/sct:sct-v4.0.0-beta.0-ubuntu-18.04
mkdir ~/docker_shared_folder
docker run -p 2222:22 --rm -it -v ~/docker_shared_folder://home/sct/docker_shared_folder neuropoly/sct:sct-v4.0.0-beta.0-ubuntu-18.04
~~~
Then opened another terminal, and ran (with error afterwards):
~~~
ssh -Y sct@localhost:2222
ssh: Could not resolve hostname localhost:2222: nodename nor servname provided, or not known
~~~

**Comment by jcohenadad** [comment]
OK, it was a macOS thing. The following syntax works:
~~~
ssh -Y -p 2222 sct@localhost
~~~

I will update the documentation (assuming the above command also works on Linux???).

However, when connecting and then calling fsleyes, i get:
~~~
Unable to access the X Display, is $DISPLAY set properly?
~~~

**Comment by zougloub** [comment]
`sct@localhost:2222` is a mistake even on Linux, fixed the docs.

**Comment by jcohenadad** [comment]
as for my X Display issue, is xquartz required on my Mac?

**Comment by zougloub** [comment]
I'd think so... I'm resetting a Mac to test that stuff.

**Comment by jcohenadad** [comment]
Display issue to be continued in https://github.com/neuropoly/sct_docker/issues/29
