### ISSUE TITLE
Is git installation really necessary?

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_docker#27]
In the README, it says git needs to be installed in order to "provide an SSH binary". I don't see what binary it is referred to here. 

Following the installation of sct-docker container, git was only used to git clone the repository in order to execute `sct-win.xlaunch`, but this could be done by simply downloading the repository as a zip file.

@zougloub can you enlighten me?

**Comment by zougloub** [comment]
Installation of git for Windows was used because off the top of my head it's an easy way to get OpenSSH utilities (ssh, ssh-keygen, ssh-copy-id... ) on Windows.

**Comment by jcohenadad** [comment]
but are OpenSSH utilities utilized at some point to run SCT and FSLeyes?  If not, I suggest we drop git installation

**Comment by zougloub** [comment]
Yes, to communicate with the container and do X11 forwarding.
