### ISSUE TITLE
Batch_processing error with Docker_toolbox

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/sct_docker#28]
### Description

batch_processing.sh return an error when running /home/sct/sct_4.0.0-beta.0/scripts/sct_process_segmentation.py -i t2_seg.nii.gz -p shape

### Steps to Reproduce

0. SCT V beta 4.0.0 on docker toolbox (docker pull)

1. execute ./batch_processing.sh

**Expected behavior:** apply different fonction without problem

**Actual behavior:** stops when running sct_process_segmentation
and yield the following error 

IndexError: index 235 is out of bounds for axis 0 with size 235

full error [here](https://pastebin.com/V7kHsT6Y)

**Comment by jcohenadad** [comment]
@lrouhier to rule out the possibility that the error has been fixed in recent versions of SCT, could you please [create a container of SCT's master branch](https://github.com/neuropoly/sct_docker#generation-and-distribution) and try again with batch_processing under docker?

**Comment by lrouhier** [comment]
I will try that.

**Comment by jcohenadad** [comment]
@lrouhier any update?

**Comment by lrouhier** [comment]
There are no image for the container with the master branch I'm trying to create one.

**Comment by jcohenadad** [comment]
yes, that's precisely what i asked [here](https://github.com/neuropoly/sct_docker/issues/28#issuecomment-517014082) ;-)

**Comment by jcohenadad** [comment]
@lrouhier any update?

**Comment by lrouhier** [comment]
With V4.0.0-beta5 (i wanted to try with the last stable release) There is no error. I think we can close the issue.
