### ISSUE TITLE
Add the new Doc regarding to use docker tools on Windows XP/VISTA/7/8/8.1/10 home 

### ISSUE THREAD

**Issue by fperdigon** [neuropoly/sct_docker#3]
This doc is destinated to the users that do not have Windows 10 pro to run Docker natively and have to use Docker tools

**Comment by jcohenadad** [comment]
doc needs to be referenced to the README of SCT, currently it points towards the VM-- this is old and should be updated

**Comment by fperdigon** [comment]
Already done. Closing this
