### ISSUE TITLE
Fsleyes not working with docker toolbox

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/sct_docker#40]
### Description

Fsleyes is not working eventhough the Xming server is running. 

### Steps to Reproduce

0. sct-4.0.0-official (Docker Toolbox on windows 10 home) 

1. Run docker run -p 2222:22 --rm -it -v c:/Users/docker_shared_folder://home/sct/docker_shared_folder neuropoly/sct:sct-4.0.0-official

2. run windows/sct-win_docker_toolbox.xlaunch (which open an emulated Xming terminal)

3. run flseyes & (in the docker quickstart terminal window) 

**Expected behavior:**  An fsleyes windows should open. 

**Actual behavior:** An error occures. the error message is Unable to access the X Display, is $DISPLAY set properly?

**Comment by lrouhier** [comment]
Solution : 
1. Run 'echo $DISPLAY' on the emulated Xming terminal
2. Copy the output address
3. Run export DISPLAY=<previously obtained address> on the docker quickstart terminal 
4. Run fsleyes & (on the docker quickstart terminal) to check if it is working


It should open a new Xming window with fsleyes running.

**Comment by jcohenadad** [comment]
@lrouhier could you please update the documentation? (create a PR)-- thanks 👍
