### ISSUE TITLE
Could I apply GM segmentation methods in normal T2WI?

### ISSUE THREAD

**Issue by zmzforever** [neuropoly/sct_docker#42]
Hi Madam/Sir,
  I am a medical student and studying for SCT now. I have read some articles about T2*WI and SCT, however, I want to do some retrospective studies, and I only have T2WI and T1WI for these patients. I'd like to know will it be possible to distinguish GM in these patients? My email address is zmzforever@pku.edu.cn. If you have any suggestions, please connect me.
  Thanks for your work. Though this tool is hard to operate for a medical student, once I have installed and tried to run on docker, it is amazing. It can not be more useful for medical research.
Sincerely,
Mavis.

**Comment by jcohenadad** [comment]
hi Mavis,
for general questions regarding SCT, could you please post on this forum:
http://forum.spinalcordmri.org/c/sct
thanks!
