### ISSUE TITLE
Xming does not open after new docker pull. 

### ISSUE THREAD

**Issue by lrouhier** [neuropoly/sct_docker#47]
email from user :
~~~
Hi,

thank you Julien, now I succesfully downloaded the 4.2.1 version but I don’t understand why I can’t open xming anymore.

When I run  “  windows/sct-win_docker_toolbox.xlaunch “   the xMing window doesn’t pop up anymore.

Could you help me with this?

Thank you
~~~~

**Comment by lrouhier** [comment]
I think the issue comes from the ECDSA fingerprint that has changed. The PC does not want to connect to an IP with a different fingerprint. I am looking into it to find a convenient  way to print and modify the .ssh/known_host file for the user

**Comment by lrouhier** [comment]
Two possible option : 
1) We fix the issue for each OS (e.g., solution for windows : )
~~~
findstr /v /c:"192.168.99.100" %USERPROFILE%\\.ssh\\known_hosts > %USERPROFILE%\\.ssh\\known_hosts.txt | type %USERPROFILE%\\.ssh\\known_hosts.txt > %USERPROFILE%\\.ssh\\known_hosts | del %USERPROFILE%\\.ssh\\known_hosts.txt
~~~

2) we create a shell script that fix this which will be os agnostic

**Comment by lrouhier** [comment]
So the shell script will look at the supposed place of .shh. We will leave instructions on how to do it manually if it is not in the supposed folder.

**Comment by jcohenadad** [comment]
@lrouhier 99.999% of users using docker will be on windows, plus: in the README, there is a separate section for Windows users, which means: everyone on this section is running Windows, so you can assume their OS is windows, meaning: you can ask them to run a line of code that will solve their problem. can you propose a change in the readme? thx!
