### ISSUE TITLE
Explain user how to map host folders to a docker container on Docker Toolbox

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/sct_docker#5]
Realistically, if we as Windows users to go with Docker install (instead of VM), then they should have persistent container running. So, instead of redirecting them to the Docker page (which can be overwhelming to some of our users), we should explain them, in simple terms, how to do it. 

In addition, we should also provide explanations about how to do essential tasks, such as accessing MRI data located in their Windows laptop into their Docker container.

**Comment by fperdigon** [comment]
work in development

**Comment by fperdigon** [comment]
@jcohenadad when you speak of persistence you mean that the user is able to install a new program in the container i.e. FSL or MRIcron and that the changes are saved in the Docker container?

**Comment by jcohenadad** [comment]
@fperdigon a more realistic scenario is that they go to docker, they copy 20 subjects, they analyze those subjects, they go to sleep, and next morning when they open docker the data should better be there ;-)

**Comment by fperdigon** [comment]
@jcohenadad, understood, that can be solved by mounting a folder of windows host systems inside the home directory of the docker container. I'm working on that for docker toolbox solution, soon I should come with a solution and documentation about it
